// <auto-generated />
using CRUD_WEBAPI_BLAZOR.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_WEBAPI_BLAZOR.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220303223824_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUD_WEBAPI_BLAZOR.Shared.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            Engine = "V8 TWIN TURBO",
                            ManufacturerId = 1,
                            Model = "488 PISTA",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Color = "White",
                            Engine = "V12",
                            ManufacturerId = 2,
                            Model = "AVENTADOR",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Color = "Silver",
                            Engine = "V10",
                            ManufacturerId = 3,
                            Model = "Carrera GT",
                            Year = 2006
                        });
                });

            modelBuilder.Entity("CRUD_WEBAPI_BLAZOR.Shared.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Italy",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Italy",
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Name = "Porsche"
                        });
                });

            modelBuilder.Entity("CRUD_WEBAPI_BLAZOR.Shared.Car", b =>
                {
                    b.HasOne("CRUD_WEBAPI_BLAZOR.Shared.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
